Add inheritance to FilterCommand
AY2223S2-CS2113-T15-1/tp pull request #115
Opened 2023-03-23 09:06 UTC by nikkiDEEE

2023-03-23 09:22 UTC, nikkiDEEE commented
This is just the FilterByTopicCommand

Nic will PR the FilterByImportanceCommand, there wont be any merge conflicts

2023-03-26 10:42 UTC, nikkiDEEE commented
Not complete, still refactoring the AddCommand so user can input the importance level

But the comparator works and it can be sorted by importance (when editing the importance in the files itself)

2023-03-27 07:18 UTC, nikkiDEEE commented
This PR does not include exception handling for strings cus its giving errors when i attempt to try-catch in the isValidImportance() method in the Parser class... will re-look at it after EG submission 

but for now the importance filter command works and user can input importance from 1-10 and it will give an error prompt if user input anything out of this range in the 'i/' field

2023-03-27 09:17 UTC, heejet requested changes

2023-03-27 09:17 UTC, heejet commented on src/main/java/seedu/clialgo/command/AddCommand.java
> +        importance = 5;
Done use magic number. Use a constant instead.

2023-03-27 09:17 UTC, heejet commented on src/main/java/seedu/clialgo/command/FilterByImportanceCommand.java
> +            System.out.println(serialNumber + ". " + cs2040CFile.getName());
I think it is better to print the importance after the name.
E.g
```
1. bubble sort [1]
```

2023-03-27 09:17 UTC, heejet commented on src/main/java/seedu/clialgo/command/FilterByImportanceCommand.java
> +            System.out.println(serialNumber + ". " + cs2040cFile.getName());
same as above

2023-03-27 09:17 UTC, heejet commented on src/main/java/seedu/clialgo/command/InvalidImportanceCommand.java
> +    }
Add in the comparison feature for this

2023-03-27 09:17 UTC, heejet commented on src/main/java/seedu/clialgo/file/CS2040CFile.java
> +        this.importance = 5;
Use constants instead of magic numbers

2023-03-28 05:14 UTC, heejet approved these changes

2023-03-28 05:17 UTC, merged