Add breaks for exceptions to match Step 2 of Ui in DG
AY2223S2-CS2113-T15-1/tp pull request #225
Opened 2023-04-03 06:26 UTC by nikkiDEEE

Added the try catch (done using breaks because seq diag no try-catch, they just use breaks) for exceptions to better represent the steps 1-3 for DG under Ui implementation

2023-04-03 06:45 UTC, heejet requested changes

2023-04-03 06:45 UTC, heejet commented on docs/sequence-diagrams/diagrams/Ui.png
When an exceptions occurs, the `Ui` calls its own `printReadFail()` method not the Scanner.

2023-04-03 07:09 UTC, heejet commented
U can refer to this also https://github.com/nus-cs2113-AY2021S2/forum/issues/53

2023-04-03 11:02 UTC, nikkiDEEE commented
> U can refer to this also [nus-cs2113-AY2021S2/forum#53](https://github.com/nus-cs2113-AY2021S2/forum/issues/53)

got it, thanks! since there isnt much nesting for mine, i went with the alt statement instead of using reference frames to explain the printReadFail method being called from the exceptions

2023-04-03 11:47 UTC, heejet commented
> > U can refer to this also [nus-cs2113-AY2021S2/forum#53](https://github.com/nus-cs2113-AY2021S2/forum/issues/53)
> 
> got it, thanks! since there isnt much nesting for mine, i went with the alt statement instead of using reference frames to explain the printReadFail method being called from the exceptions
> 
> should i add `note over Ui` for the 2 exceptions stating `fullCommand == EXIT_COMMAND` is returned?

Yes that would be better

2023-04-03 12:26 UTC, nikkiDEEE commented on docs/sequence-diagrams/diagrams/HelpFeature.png
I have made the changes for this in the latest push to this PR

2023-04-03 12:42 UTC, heejet commented
> 
 I think your current diagram is fine just that you forgot to put in the type. `FullUserInput` should be `FullUserInput: String` and `EXIT_COMMAND` should be `EXIT_COMMAND: String`

2023-04-03 16:44 UTC, nikkiDEEE commented
> > 
> 
> I think your current diagram is fine just that you forgot to put in the type. `FullUserInput` should be `FullUserInput: String` and `EXIT_COMMAND` should be `EXIT_COMMAND: String`

yup added

2023-04-04 11:45 UTC, heejet approved these changes

2023-04-04 11:48 UTC, heejet approved these changes
Looks good to merge after resolving conflicts

2023-04-04 14:30 UTC, merged