Branch code review fix v2.1
AY2223S2-CS2113-T15-1/tp pull request #228
Opened 2023-04-03 09:46 UTC by nikkiDEEE

2023-04-03 10:33 UTC, heejet requested changes

2023-04-03 10:33 UTC, heejet commented on src/main/java/seedu/clialgo/Ui.java
> +    private static final String CODE_LABEL = "[CODE] ";
I think the concept of replacing magic strings with constants is to improve code readability. If things like `.` and ` ` are replaced by constants i think it is over excessive. For `[` and `]`, I think putting it inside a method is sufficient.
![image](https://user-images.githubusercontent.com/88279614/229485021-3886add4-348b-4ebf-968c-3ac9c2830d50.png)

I think `[NOTE]` and `[CODE]` should be replaced with constants but the rest I think is not necessary.
What do you guys think @nicholas132000 @ong-ck @lohjooh

2023-04-03 11:38 UTC, nicholas132000 commented on src/main/java/seedu/clialgo/Ui.java
> +    private static final String CODE_LABEL = "[CODE] ";
![image](https://user-images.githubusercontent.com/88270205/229497921-2424d927-b0b3-4b60-9a21-556b90577623.png)
According to sources online, string constants are used so that we do not need to type out the same thing multiple times. In this case, since the string constants for e.g. `LEFT_SQUARE_BRACKET` is more of a hassle to type that `[`, i think that your suggestion is valid.

2023-04-03 11:51 UTC, nikkiDEEE commented on src/main/java/seedu/clialgo/Ui.java
> +    private static final String CODE_LABEL = "[CODE] ";
i agree with the over-excessiveness, but it looked rather inconsistent in the method when `LEFT_SQUARE_BRACKET` was used alongside a `". "`, so i decided to use string constants all the way. thoughts?

@nicholas132000 our TA recommended using string constants in the code review for my part #221 

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/88139349/229500888-d76fd966-988d-4619-9bfb-2a2cb7d24c84.png">

2023-04-03 12:34 UTC, heejet commented on src/main/java/seedu/clialgo/Ui.java
> +    private static final String CODE_LABEL = "[CODE] ";
In mine he said can either use constants or just use a method

2023-04-03 16:31 UTC, nikkiDEEE commented on src/main/java/seedu/clialgo/Ui.java
> +    private static final String CODE_LABEL = "[CODE] ";
Okay see what the rest think ig

2023-04-04 15:47 UTC, ong-ck commented on src/main/java/seedu/clialgo/Ui.java
> +    private static final String CODE_LABEL = "[CODE] ";
I am of similar opinion with @heejet in the using of a method to replace the magic strings instead of creating constants for the symbols used. The creating of constants for `NOTE_LABEL` and `CODE_LABEL` is definitely preferred but the others might really be a little excessive.

2023-04-05 02:30 UTC, nikkiDEEE commented on src/main/java/seedu/clialgo/Ui.java
> +    private static final String CODE_LABEL = "[CODE] ";
ok! will make the changes then

2023-04-05 02:50 UTC, nikkiDEEE commented
removed excessive string constants

2023-04-05 05:13 UTC, heejet approved these changes
LGTM

2023-04-05 05:14 UTC, merged