Add Junit test to AddCodeCommand
AY2223S2-CS2113-T15-1/tp pull request #233
Opened 2023-04-05 04:01 UTC by nicholas132000

2023-04-05 05:17 UTC, heejet requested changes

2023-04-05 05:17 UTC, heejet commented on src/test/java/seedu/clialgo/command/AddCodeCommandTest.java
> +        }
Why is this blank?

2023-04-05 05:18 UTC, heejet commented on src/test/java/seedu/clialgo/command/AddCodeCommandTest.java
> +        }
If you expect invalid command to be printed, why is the expected output the empty string?

2023-04-05 06:16 UTC, nicholas132000 commented on src/test/java/seedu/clialgo/command/AddCodeCommandTest.java
> +        }
Will make the edits!

2023-04-05 08:45 UTC, ong-ck reviewed
Might want to replace the magic string ".cpp" as well

2023-04-05 08:45 UTC, ong-ck commented on src/main/java/seedu/clialgo/command/AddCodeCommand.java
> +        return Objects.equals(this.name, otherAddCodeCommand.name);
To check for equality of AddCodeCommand, do you also need to check whether the topic and importance are the same as well?

2023-04-05 10:52 UTC, heejet requested changes

2023-04-05 10:52 UTC, heejet commented on docs/team/nicholas.md
change the filename to ur github username.md

2023-04-06 01:54 UTC, nicholas132000 commented on src/main/java/seedu/clialgo/command/AddCodeCommand.java
> +        return Objects.equals(this.name, otherAddCodeCommand.name);
im not too sure, what do you suggest?

2023-04-06 07:00 UTC, heejet commented on src/main/java/seedu/clialgo/command/AddCodeCommand.java
> +        return Objects.equals(this.name, otherAddCodeCommand.name);
I agree with @ong-ck

2023-04-06 07:16 UTC, ong-ck commented on src/main/java/seedu/clialgo/command/AddCodeCommand.java
> +        return Objects.equals(this.name, otherAddCodeCommand.name);
Maybe you could consider this

```suggestion
        public boolean equals(Command otherCommand) {
            AddCodeCommand otherAddCodeCommand = (AddCodeCommand) otherCommand;
            boolean isNameEqual = Objects.equals(this.name, otherAddCodeCommand.name);
            boolean isTopicEqual = Objects.equals(this.topic, otherAddCodeCommand.topic);
            boolean isImportanceEqual = this.importance == otherAddCodeCommand.importance;
            return isNameEqual && isTopicEqual  && isImportanceEqual;
        }
```

2023-04-06 07:17 UTC, nicholas132000 commented on src/main/java/seedu/clialgo/command/AddCodeCommand.java
> +        return Objects.equals(this.name, otherAddCodeCommand.name);
okay, will make changes

2023-04-06 07:24 UTC, nicholas132000 commented on src/main/java/seedu/clialgo/command/AddCodeCommand.java
> +        return Objects.equals(this.name, otherAddCodeCommand.name);
is my current one okay? i combined 3 of them into the return statement

2023-04-06 08:28 UTC, nicholas132000 commented on src/main/java/seedu/clialgo/command/AddCodeCommand.java
> +        return Objects.equals(this.name, otherAddCodeCommand.name);
ohh right

2023-04-06 13:27 UTC, heejet approved these changes

2023-04-06 13:27 UTC, merged